---
abstract: 'This is a library of tools for managing podcast subscriptions. It comes with a command-line tool, fetch_pods.pl, that can run under Cron to keep a directory of subscribed Podcasts feeds up to date.'
author:
  - 'Lincoln Stein E<lt>lstein@cshl.orgE<gt>.'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MP3-PodcastFetch
provides:
  MP3::PodcastFetch:
    file: lib/MP3/PodcastFetch.pm
    version: 1.05
  MP3::PodcastFetch::Feed:
    file: lib/MP3/PodcastFetch/Feed.pm
    version: 0
  MP3::PodcastFetch::Feed::Channel:
    file: lib/MP3/PodcastFetch/Feed/Channel.pm
    version: 0
  MP3::PodcastFetch::Feed::Item:
    file: lib/MP3/PodcastFetch/Feed/Item.pm
    version: 0
  MP3::PodcastFetch::TagManager:
    file: lib/MP3/PodcastFetch/TagManager.pm
    version: 0
  MP3::PodcastFetch::XML::SimpleParser:
    file: lib/MP3/PodcastFetch/XML/SimpleParser.pm
    version: 0
requires:
  Config::IniFiles: 2.00
  Date::Parse: 2.20
  HTML::Parser: 3.50
  LWP: 5.8
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.05
