---
name: MP3-PodcastFetch
version: 1.01
author:
  - Lincoln Stein E<lt>lstein@cshl.orgE<gt>.
abstract: 'This is a library of tools for managing podcast subscriptions. It comes with a command-line tool, fetch_pods.pl, that can run under Cron to keep a directory of subscribed Podcasts feeds up to date.'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Config::IniFiles: 2.00
  Date::Parse: 2.20
  HTML::Parser: 3.50
  LWP: 5.8
  perl: 5.8
provides:
  MP3::PodcastFetch:
    file: lib/MP3/PodcastFetch.pm
    version: 1.01
  MP3::PodcastFetch::Feed:
    file: lib/MP3/PodcastFetch/Feed.pm
  MP3::PodcastFetch::Feed::Channel:
    file: lib/MP3/PodcastFetch/Feed/Channel.pm
  MP3::PodcastFetch::Feed::Item:
    file: lib/MP3/PodcastFetch/Feed/Item.pm
  MP3::PodcastFetch::TagManager:
    file: lib/MP3/PodcastFetch/TagManager.pm
  MP3::PodcastFetch::XML::SimpleParser:
    file: lib/MP3/PodcastFetch/XML/SimpleParser.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
